# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Beautiful' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Beautiful

pod 'GPUImage', '~> 0.1.7'
  target 'BeautifulTests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'DrowningGraphicer', '~> 0.1.0'
  target 'BeautifulUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
